### ISSUE TITLE
Implementera lightmode styling på hela applicationen

### ISSUE THREAD

**Issue by mirrenil** [mirrenil/Prilla-examensarbete#77]
- [x] Bakgrundsfärg: #fff
- [x] Navbarfärg: #fff
- [x] Separators färg: #D3D3D3
- [x] Aktiviteter ikoner transparenta med border color:  #783bc9
- [x] Gillade aktiviteter ikoner färg: #783bc9
- [x] Settings ikonfärg: #000
- [ ] Recension bakgrundsfärg: #7e7885
- [x] Recension text: #fff
- [ ] Detaljsida tab: #99999
- [ ] Detaljsida info aktiv tab: #382f44
- [ ] Detailjsida styrka: #000
- [ ] Detailjsida rating: #783bc9
- [x] Profilsida följknapp: #FFFD54 border: #783bc9
- [x] Profilsida följerknapp: #fff border: #783bc9

**Comment by mirrenil** [comment]
![Image](https://user-images.githubusercontent.com/90900256/210763365-68324954-9e8c-4ee5-9a6f-84f358968957.png)
![Image](https://user-images.githubusercontent.com/90900256/210763366-e90e2c8c-98d8-49ec-a278-df8309dadd58.png)
